#!/usr/bin/env python
"""
Process cluster-based power simulation results and plot empirical power.

This script:
1. Resolves the result filename pattern.
2. Infers the block/subject grid from filenames.
3. Uses user-provided block/subject labels when they align safely.
4. Falls back to inferred file indices with warnings when labels do not align.
"""

import sys
from pathlib import Path

import numpy as np

# Add the project root so the sibling fnirspower_py package is importable.
SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from fnirspower_py.process_data import (
    empirical_power_summary,
    find_result_pattern,
    infer_result_grid,
    load_summary_grid,
    resolve_plot_inputs,
)
from fnirspower_py.plot_utils import plot_grid_curves

if __name__ == "__main__":
    # -----------------------------------------------------------------
    # User inputs
    # -----------------------------------------------------------------
    date2use = "9999-99-99"

    data_dir = Path("/path/to/python/data")
    save_dir = Path("/path/to/python/results/")  # change this
    plots_dir = save_dir / "plots"

    # These should match the grid used in
    # sim_cluster_based_power_parallelized.py.
    blocks = np.array([5, 20, 40], dtype=float)
    subjects = np.array([5, 15, 30, 45, 60], dtype=int)

    # Use None to plot all block counts, or provide filename block indices.
    plot_bbs = None

    # Match the title generated by the simulation script.
    result_label = "signal_vs_null_hbo_roi00_power_test"

    candidate_patterns = [
        f"{date2use}_{result_label}_block{{bb:02d}}_subj{{ss:02d}}.pkl",
        (
            f"{date2use}_results_{result_label}"
            "_block{bb:02d}_subj{ss:02d}.pkl"
        ),

        # Backward-compatible patterns from older runs.
        (
            f"{date2use}_signal_vs_null_hbo_power_test"
            "_block{bb:02d}_subj{ss:02d}.pkl"
        ),
        (
            f"{date2use}_results_signal_vs_null_hbo_power_test"
            "_block{bb:02d}_subj{ss:02d}.pkl"
        ),
        (
            f"{date2use}_results_type1_null"
            "_block{bb:02d}_subj{ss:02d}.pkl"
        ),
    ]

    # -----------------------------------------------------------------
    # Resolve file pattern and infer grid from filenames
    # -----------------------------------------------------------------
    file_pattern = find_result_pattern(save_dir, candidate_patterns)
    print(f"Using file pattern: {file_pattern}")

    bb_found, ss_found = infer_result_grid(save_dir, file_pattern)
    print(f"Found {len(bb_found)} block index/indices: {bb_found}")
    print(f"Found {len(ss_found)} subject index/indices: {ss_found}")

    block_labels, subject_labels, plot_rows = resolve_plot_inputs(
        blocks=blocks,
        subjects=subjects,
        plot_bbs=plot_bbs,
        bb_found=bb_found,
        ss_found=ss_found,
    )

    # -----------------------------------------------------------------
    # Load and summarize
    # -----------------------------------------------------------------
    summary_grid = load_summary_grid(
        data_dir=save_dir,
        file_pattern=file_pattern,
        bb_found=bb_found,
        ss_found=ss_found,
        summary_fn=empirical_power_summary,
    )

    print("Summary grid shape:", summary_grid.shape)
    print("Summary grid:")
    print(summary_grid)

    # -----------------------------------------------------------------
    # Plot
    # -----------------------------------------------------------------
    ymax = max(0.10, float(np.max(summary_grid)) * 1.1)
    out_fig = plots_dir / f"{date2use}_{result_label}.png"

    plot_grid_curves(
        subjects=subject_labels,
        blocks=block_labels,
        summary_grid=summary_grid,
        plot_bbs=plot_rows,
        out_fig=out_fig,
        title=f"Power ({result_label})",
        xlabel="Sample Size",
        ylabel="Power",
        horizontal_line=0.80,
        ylim=(0, ymax),
        legend_title="Block Count",
    )

    print(f"Saved plot to {out_fig}")
